# Generated by Django 5.1.4 on 2024-12-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction', models.TextField()),
                ('booklet', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
